version: "3.7"

services:

    try8_redis:
      container_name: try8_redis
      image: redis:alpine

    try8_postgres:
      container_name: try8_postgres
      image: postgres:alpine
      volumes:
         - "./sourcefiles/postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
       - "54320:5432"
#      networks:
#            testing_net:
#                ipv4_address: 172.28.1.2

    try8_nginx:
      container_name: try8_nginx
      image: nginx:alpine
      working_dir: /application
      volumes:
          - "./application:/application"
          - "./sourcefiles/nginx/conf.d:/etc/nginx/conf.d"
          - "./sourcefiles/nginx/log:/var/log/nginx"
      ports:
       - 8500:80
#      networks:
#            testing_net:
#                ipv4_address: 172.28.1.3

    try8_php:
      container_name: try8_php
      build:
        context: sourcefiles/php/7.4_fpm
        args:
          UID: ${UID:-1001}
          GID: ${GID:-1001}
          USR: ${USR:-www-data}
      working_dir: /application
      volumes:
        - "./application:/application"
        - ./sourcefiles/php/myphp.ini:/usr/local/etc/php/conf.d/myphp.ini
#      networks:
#          testing_net:
#              ipv4_address: 172.28.1.4

#networks:
#    testing_net:
#        ipam:
#            driver: default
#            config:
#                - subnet: 172.28.0.0/16